# ~/.config/alacritty/alacritty.toml

[window]
dimensions = { columns = 80, lines = 25 }
decorations = "None"
dynamic_title = false

[font]
normal = { family = "Source Code Pro", style = "Regular" }
size = 9.0

[colors.primary]
foreground = "#C5C8C6"
background = "#181818"

[colors.normal]
black = "#232323"
red = "#FF000F"
green = "#8CE10B"
yellow = "#FFB900"
blue = "#008DF8"
magenta = "#9A5FEB"
cyan = "#00D8EB"
white = "#FFFFFF"

[colors.bright]
black = "#444444"
red = "#FF2740"
green = "#ABE15B"
yellow = "#FFD242"
blue = "#0092FF"
magenta = "#9A5FEB"
cyan = "#67FFF0"
white = "#FFFFFF"

[mouse]
hide_when_typing = true

